language: java
jdk:
- oraclejdk8
script: mvn package cf:push -Dcf.password=$PASSWORD
branches:
  only:
  - master
env:
  global:
    secure: ClkDiBPaZYOrFKIgoQVfnlME+l1RgstFNzmdHlnSt2h5UTsVDAYV8+ly/AUcGLrTeiEi5QFfWxBg5Z2pk1ApwQV64I3mwCustUItfCwL57VgC42EihAHvNOz+SR41SledB69xJnkjI2u5NSY2uzK/1IiS0JBGZxI8amoXVigLHppcCfwYfqvu8dc0P+JaCKJWok+nSK8C3CMr/dl0irn4UcHLKzBnNstaD4/Bw+9ONNz4H8HRSONn1G68w4FuSKOrYisevAOa5pwQN/wNv4iOp2xzURwabxwe2gB55XNVNvjk4ylpOS6ggMIV9uwFpGKD8gD5NJVkMXBRBSGpRBVrPRvPGANBq2ky+j5Sy7Z3NxaxG2qIr0TsPzmaNq1IqmfJYE8Pbp9KWMHiHfWDv6z/PDcHmJaq64edbsMnC4v2YrUV/CKNNlluN2Uym2OrQ+nTrbs47QEV4WOEQKN+c9i2L1oWdeXBqON2rBB2JZlnsadm8tAGYOkC9jjioZXCkxN3Ja+c+l4S+WievQQLm7XIi5GiiUDn0D3fRAFSOMwmHg8R8c95jtiQW2NxybcUmwlglSXbmwMcyEIjYZoZmlLDQtYhJzoi8g83UCAfaDRuMN5cGFVYJwauBj5oZLu6z2VITUn7WoZjcH0uKpUB8FPkIdlFqR4C0Zj1XqiM6/XxAU=
