language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: roger.villars@bluewin.ch
  password:
    secure: gs5M5BWfNkE8k0ZUN4JIsEDFmM9AAKVG9LJFYB3XKr5TsV1i6uy6QtSfvRLgXLWb9oEO3/7IA2jb0qFZjg5d8Qj19zyGiFoaR1yzDxl2ToFxjcLulM1Lwqy/Luq10sHFj05LlG9/l6EGDjHipfelNf+aAZuoUZly7hejeUKT4qbmXw35rlxDTZJqgHyI0FCPVw/zoAahSWzsevauvM+TSs7N6vo6TXMnEM53i21Tal60I7YumR0ANDBnzb+Jqx1Sql+NabmmPTMIMTz4ADY2Jr3wciMv4GlZ7fdAPO9nAnQfDK5LKswDaNMSAJbTedwWzlHroRxhoRE+3N1ZY/oieAqn9yvYHkY9dwPNYaaldJdETJM3SG90unevjRhCH+RcHuOxryD+6jMAWbS+otLsKCGPF1x318YvJH0ltqxa9CU2ftbfO5oJCC07tcGX29uJMP7RUMgk4L3P7epq8YVYH7PoyLqZXBraiScx4bKYqynTrMD0E3ed4BvKxPYAtQ2Vt5I+iZe0J2PZg7mwcupos+5LuLHdn50fKon6qNwRxGcwscJOOd9P2iUYWmkRUK3qiAd7o0cyo1uETHNwG5R4axmvv3SqtfqZQs0t4/aJWnXiaBOB7GKmr7FDItzp8G7K2S58Sk9vR6eUfIw6O01LRJMGjzX3/+79vkPz6NwdfqI=
  organization: bigendian
  space: development
