language: java
jdk:
- oraclejdk8
env:
  global:
    secure: YmtMlyYX78VO4JxLmFoOSRPItBPHNc0uIGho897uBghdULuHVOwaxhNV5ZW9VAwqtofvdlyCIdELOFHLWxeH+5xsNlWq1H6Ps4yPC67Iof8J8CJ07yszLUpktFh+XDHEDZt4hRg3SUV0JPR6AIBCx1uqXQpy0gRwtQU5pmuMRFA/Hqc2/RF8JSMgLLRoGZv6SO2d+DOgn6Sq5ctsa+xGA3RS52ZPeDtFV6OrQRxTz6z3x63FXwm9zxtMqzkjuKX4Nn8t9yMA0fLdIOHq90sFA5fUSFhNpd8/GrqQ82otwRN5f5Bp3djpz99dfW3RrSoNB7iTqeR0q6LuXQ+8BZifJHOSeExx4ZmvfWuxQ8XcJGpvN9+OFWaZ5eZfCI2echRg9jRLMEum2g/qQW3QHdXyVKHjOTLTKIdG05mng3sl+Wnbtwahcbd46+EblkZPzN0RpKoHACc9wuO4ejVWxxSz1FlC7ScVj57tIe2RpeS3H0wubRfN17EKyxXktJDU4Tp6b4/evYBzb/4s8Q8vxvoWPvoqunR0UZjnmONGl9G3n2d2fHLCqnJcIHCI8V8TJHKSN1TXBk5Ynbumri74xqocJw1H8cbDpWPsl2sH6ncpqyD2dcY4rn5BCP2jwkzj3BrpHlwfO1SCK6P4hHpCqS9sz7/P9U1EMDDq+HCEkMbSfC0=
script: mvn package cf:push -Dcf.password=$PASSWORD
branches:
  only:
  - master
