language: java
jdk:
- oraclejdk8
env:
  global:
    secure: aU8ZGRjehNiqOdL11rXfl6Gh+GsKuZ2VAJhLtukMFcPfHwMngopw7/KfByanOSmni5hEsZcF3u42PELVzd0FRgQ3SeWYIgn3krTDU+Jbk2p8Yd4ALOEyTg34S1TsT1mkpCROluYmNYS5yoEQfZe20cKj1+i5gr+boKjecJS9F1SeJD+FRz0Upo9oFyzyq3zgeAleE+y87GUhRRXR2FaH20Y61AFJkRGs5SRV4x8/hOupwjzl9UJEfX/pugMWAJhHjnvmshsH2IwoBVcJgaUGhpSX4XlcexWigAh52KXpqxRTEGyj3BGoDf53SmMvD8R6HRMoPmsLK4M0UVKfKlXgyPmHpaRIFiYTdLH1GrDrxY4JlSUkOao3RgZIKt9v6g8evSRlWjAAjLSseqrHXtfERc9QZ62cW4amYTCN5VdaxxyqUsLoh8BKazpUIu0Gm+6l1VmMd7Kp43aH46OTuDoFDt8zEWVX9sRSACF+deXABW0Y0xrmFf9GiTVInIKxMfogi1+2k+bnMnSIDhSRiWF8hjbASt3Me3qT0wFhbvw9JrvUudPSSEbJXrOO/kHopdcZhN86QymofowXyk1Zfwg5IO3irrxWkRUKNs7rCsn/VCJOvlI7mXCWM2OqZoxR4EeStX2cuJFaVB8XNHYJLLPmkOPsqnn5E68mTyTwGqToDGI=
script: mvn package cf:push -Dcf.password=$PASSWORD
branches:
  only:
  - addon-templates
